### ISSUE TITLE
roadmap for HA integration?

### ISSUE THREAD

**Issue by scruysberghs** [XKNX/xknxproject#324]
Hi guys, 

Nice work on this project. Playing around with HA KNX integration lately myself (long time HA user, newish to KNX due to a full house renovation). I see unreleased features like the group adress tree view in the repo. Is there more work planned for this to make it it autocreate entities in HA? Was thinking about getting the cobwebs of my Python skills a work on a yaml file creator using the xknxproject module but if this is already WIP I can try to join the effort.

Regards
Steven

**Comment by farmio** [comment]
Hi 👋! 
We are indeed currently working on a "UI entity creation" feature (not *auto*create, but create). Feel free to join us on the xknx discord server or have a look at https://github.com/XKNX/knx-frontend/discussions

There are unreleased features currently as we are still juggling ideas to get a decent UX design. We also have found some shortcomings of `xknxproject` that we needed to address first.

As for the roadmap: there is none. Since all of this is a spart-time hobby project, we can't make promises for features or release schedules.
